remote_theme: CarolinaPB/CarolinaPB.github.io
title: Mapping and variant calling
author: Carolina Pita Barros

navbar-links:
  About Me: "aboutme"
  Pipelines:
    - Mapping and variant calling (short reads): https://carolinapb.github.io/WUR_mapping-variant-calling/
    
# --- Footer social media links --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "carolina.pitabarros@wur.nl"
#   facebook: deanattali
  github: CarolinaPB
#   twitter: daattali
#   patreon: DeanAttali
#   youtube: c/daattali
#  medium: yourname
#  reddit: yourname
  linkedin: "carolina-pita-barros-671077155"
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  ORCID: your ORCID ID
#  google-scholar: your google scholar

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false
